version: "3"

tasks:
  build:
    cmds:
    - >-
      latexmk -xelatex
      ru-ops.tex
      en-ops.tex
    sources:
    - ./picture.jpg
    - ./**/*.tex
    generates:
    - ./**/*.pdf
  clean:
    cmds:
    - >-
      rm
      *.xdv
      *.fls
      *.aux
      *.fdb_latexmk
      *.log
      *.out
