version: "3"

tasks:
  build:
    cmds:
    - |
      latexmk {{.FLAGS}} \
        ru-go.tex \
        ru-ops.tex \
        ru-fullstack.tex
    sources:
    - ./**/*.tex
    generates:
    - ./**/*.pdf
    vars:
      FLAGS: -xelatex
