version: "3"

tasks:
  build:
    cmds:
    - |
      latexmk {{.FLAGS}} \
        ru-ops.tex \
        en-ops.tex \
    sources:
    - ./picture.jpg
    - ./**/*.tex
    generates:
    - ./**/*.pdf
    vars:
      FLAGS: -xelatex
