name: Build CV

on:
  push:
    branches:
    - master

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build PDFs
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add font-noto
            latexmk -xelatex \
              ./ru-go.tex \
              ./ru-fullstack.tex \
              ./ru-ops.tex
      - name: Create release with PDF assets
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            ./ru-go.pdf
            ./ru-fullstack.pdf
            ./ru-ops.pdf
          name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
