name: Build CV

on:
  push:
    branches:
      - master

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build PDFs
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add font-noto
            latexmk -xelatex \
              ./en-ops.tex \
              ./ru-ops.tex
            mv \
              en-ops.pdf \
              EN_Timur_Demin_DevOps_Engineer.pdf
            mv \
              ru-ops.pdf \
              RU_Timur_Demin_DevOps_Engineer.pdf
      - name: Create release with PDF assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./EN_Timur_Demin_DevOps_Engineer.pdf
            ./RU_Timur_Demin_DevOps_Engineer.pdf
          name: CV (PDF)
          tag_name: latest
          body: |
            See "Assets" below for PDF files.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
